language: objective-c
osx_image: xcode61
rvm:
- 2.4.0
env:
  global:
    - UNITY_VERSION=5.5.0p4
    - UNITY_HASH=2f9c3a0f4141
  matrix:
  - PLATFORM=android
  - PLATFORM=ios
before_install:
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh
install:
- ./Scripts/install.sh
script:
- mkdir -p ./Assets/Editor
- cp ./Scripts/BatchBuild.cs ./Assets/Editor/BatchBuild.cs
- ./Scripts/build.sh
cache:
  directories:
    - /Applications/Unity
